EXE = a.out
CXX = c++
CFLAGS = -I include -g -std=c++11 -Wall -Wextra

SRC = mainBernoulli.cc src/Bandit.cc src/BernoulliBandit.cc src/Experiment.cc
OBJ=$(SRC:.cc=.o)
INC = $(wildcard *.h)

all: $(EXE)

clean:
	$(info clean up)
	@rm -rf $(OBJ) $(EXE) src/*~ include/*~ *~ 
	
.PHONY: clean

%.o: %.cc
	$(CXX) -c $< -o $@ $(CFLAGS)

$(EXE): $(OBJ)
	$(CXX) $^ -o $(EXE)

main.o: include/BernoulliBandit.h include/Bandit.h include/Experiment.h

src/Bandit.o: include/Bandit.h
src/BernoulliBandit.o: include/Bandit.h include/BernoulliBandit.h
src/Experiment.o: include/Bandit.h include/Experiment.h
